[features]
seeds = false
skip-lint = false

[programs.localnet]
social_token_platform = "CFv7S7oqqJNP24damGJA4XpHfSMJLzyhCSNjkRmXMjAe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
